 CREATE DATABASE GHOSTBUSTERS
 
 USE GHOSTBUSTERS
 
 CREATE TABLE PERFIL
 (
	COD_PERFIL INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL
 )
 
 CREATE TABLE IMAGEM
 (
	COD_IMAGEM INT IDENTITY(1,1)PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	BASE_DATA VARCHAR(MAX) NOT NULL,
 )
 
 CREATE TABLE USUARIO
 (
	COD_USUARIO INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(250) NOT NULL UNIQUE,
	SENHA VARCHAR(20) NOT NULL,
	COD_PERFIL INT NOT NULL,
	COD_IMAGEM INT, 
	FOREIGN KEY (COD_PERFIL)
		REFERENCES PERFIL(COD_PERFIL),
	FOREIGN KEY (COD_IMAGEM)
		REFERENCES IMAGEM(COD_IMAGEM)	
 )

CREATE TABLE STATUS
(
	COD_STATUS INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	COD_PERFIL INT,
	FOREIGN KEY (COD_PERFIL)
		REFERENCES PERFIL(COD_PERFIL)
)

CREATE TABLE CATEGORIA
(
	COD_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) 	
)


CREATE TABLE CHAMADO
(
	COD_CHAMADO INT IDENTITY (1,1) PRIMARY KEY,
	TITULO VARCHAR(250) NOT NULL,
	DESCRICAO VARCHAR(1000) NOT NULL,
	DATA_CHAMADO DATETIME NOT NULL DEFAULT GETDATE(),
	COD_STATUS INT NOT NULL,
	COD_CATEGORIA INT NOT NULL, 
	COD_OWNER INT NOT NULL,
	COD_TECH INT DEFAULT NULL,
	FOREIGN KEY (COD_STATUS)
		REFERENCES STATUS(COD_STATUS),
	FOREIGN KEY (COD_CATEGORIA)
		REFERENCES CATEGORIA(COD_CATEGORIA),
	FOREIGN KEY (COD_OWNER)
		REFERENCES USUARIO(COD_USUARIO),
	FOREIGN KEY (COD_TECH)
		REFERENCES USUARIO(COD_USUARIO)	
)

INSERT INTO PERFIL(NOME)
	VALUES
		('Admin'),
		('Usuario'),
		('Técnico')
	
INSERT INTO USUARIO(NOME, EMAIL, SENHA, COD_PERFIL)
	VALUEs
		('Adimin','adimin@hotmail.com','adimin',1),
		('Ghostbursters','Ghostbursters@hotmail.com','ghostbursters',1)





		

	
	